name: Android CD(Firebase)

on:
    workflow_dispatch:
        inputs:
            release_notes:
                description: "Enter release notes for this release"
                required: true

jobs:
    distribute:
        name: Distribute App
        runs-on: ubuntu-latest

        steps:
            # 1. Checkout 코드
            -   name: Checkout code
                uses: actions/checkout@v4

            # 2. JDK 설정
            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'temurin'
                    cache: gradle

            # 3. APK 빌드
            -   name: Build APK
                run: ./gradlew build

            # 4. Firebase CLI 설치
            -   name: Install Firebase CLI
                run: npm install -g firebase-tools

            # 5. 서비스 계정 키 설정
            -   name: Set up Firebase Service Account
                env:
                    FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
                run: echo "${FIREBASE_SERVICE_ACCOUNT_KEY}" > firebase-service-account.json

            # 6. Firebase App Distribution 업로드
            -   name: Upload APK to Firebase
                env:
                    GOOGLE_APPLICATION_CREDENTIALS: firebase-service-account.json
                run: |
                    firebase appdistribution:distribute \
                    app/build/outputs/apk/release/app-release.apk \
                    --app ${{ secrets.FIREBASE_APP_ID }} \
                    --groups testers \
                    --release-notes "${{ github.event.inputs.release_notes }}"

